# **Author: Mukti Prabowo**

In [1]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import scipy.sparse as sp

# **Load Data**

In [2]:
df = pd.read_csv('/kaggle/input/datasets/souravghosh999/laptop-specifications-and-prices-smartprix/smartprix_laptop.csv')
df

,img,name,processor,cores,ram,storage,graphics_card,screen_size,os,warranty,rating,score,price,threads,disk_type,screen_size.1,screen_pixels,has_touchScreen
0,https://cdn1.smartprix.com/rx-iH0EKqLhw-w280-h...,Huawei MateBook Fold Laptop,Kirin X90,10 Cores,32 GB RAM,2 TB,NaN,"18 inches, 3296 x 2472 pixels, Touch Screen",HarmonyOS 5,1 Year Warranty,4.05,61,319930,NaN,SSD,18 inches,3296 x 2472 pixels,1
1,https://cdn1.smartprix.com/rx-iRe7ozJWD-w280-h...,Lenovo V15 G4 ‎82C70081GE Laptop,7th Gen AMD Ryzen 5 7520U,Quad Core,16 GB DDR5 RAM,512 GB,Integrated AMD Radeon 610M Graphics,"15.6 inches, 1920 x 1080 pixels",Windows 11 OS,1 Year Warranty,4.35,61,33890,8 Threads,SSD,15.6 inches,1920 x 1080 pixels,0
2,https://cdn1.smartprix.com/rx-ivl17P4n6-w280-h...,Dell G15-5530 Gaming Laptop,13th Gen Intel Core i5 13450HX,10 Cores (6P + 4E),16 GB DDR5 RAM,1 TB,6 GB NVIDIA GeForce RTX 3050,"15.6 inches, 1920 x 1080 pixels",Windows 11 OS,1 Year Warranty,4.60,68,66800,16 Threads,SSD,15.6 inches,1920 x 1080 pixels,0
3,https://cdn1.smartprix.com/rx-ioXEIfxVI-w280-h...,Acer One 14 Z8-415 Laptop,11th Gen Intel Core i3 1115G4,Dual Core,8 GB DDR4 RAM,512 GB,‎Intel Iris Xe Graphics,"14 inches, 1920 x 1080 pixels",Windows 11 OS,1 Year Warranty,4.05,54,22990,4 Threads,SSD,14 inches,1920 x 1080 pixels,0
4,https://cdn1.smartprix.com/rx-ifsyyr3XR-w280-h...,HP Victus 15-fb3012AX Gaming Laptop,8th Gen AMD Ryzen 5 8645HS,Hexa Core,16 GB DDR5 RAM,512 GB,6 GB NVIDIA GeForce RTX 3050,"15.6 inches, 1920 x 1080 pixels",Windows 11 OS,1 Year Warranty,4.10,72,66240,12 Threads,SSD,15.6 inches,1920 x 1080 pixels,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,https://cdn1.smartprix.com/rx-ineILIcn0-w280-h...,Dell Vostro 3530 Laptop,13th Gen Intel Core i3 1305U,5 Cores (1P + 4E),8 GB DDR4 RAM,512 GB,Intel Integrated Graphics,"15.6 inches, 1920 x 1080 pixels",Windows 11 OS,1 Year Warranty,4.70,51,34990,6 Threads,SSD,15.6 inches,1920 x 1080 pixels,0
943,https://cdn1.smartprix.com/rx-iAx4r5Z5M-w280-h...,HP 14-ew0153TU Laptop,13th Gen Intel Core i7 1355U,10 Cores (2P + 8E),16 GB LPDDR5x RAM,1 TB,Intel Integrated Intel Iris Xe,"14 inches, 2880 x 1800 pixels",Windows 11 OS,1 Year Warranty,4.35,60,95990,12 Threads,SSD,14 inches,2880 x 1800 pixels,0
944,https://cdn1.smartprix.com/rx-i1fCFfykQ-w280-h...,Acer Swift Go 14 SFG14-72T Laptop,Intel Core Ultra 5 Series 1 125H,14 Cores (4P + 8E + 2LP-E),16 GB LPDDR5X RAM,512 GB,Intel Integrated ARC Graphics,"14 inches, 1920 x 1200 pixels",Windows 11 OS,1 Year Warranty,4.50,56,75999,18 Threads,SSD,14 inches,1920 x 1200 pixels,0
945,https://cdn1.smartprix.com/rx-ixvkK8N7E-w280-h...,HP Pavilion 15-eh1047AU Laptop,5th Gen AMD Ryzen 5 5500U,Hexa Core,16 GB DDR4 RAM,1 TB,AMD Radeon Graphics,"15.6 inches, 1920 x 1080 pixels",Windows 11 OS,1 Year Warranty,4.00,62,56990,12 Threads,SSD,15.6 inches,1920 x 1080 pixels,0
946,https://cdn1.smartprix.com/rx-i5CETlCe7-w280-h...,Acer Aspire Lite 15 AL15-52 Laptop,12th Gen Intel Core i3 1215U,Hexa Core (2P + 4E),16 GB DDR4 RAM,1 TB,Intel UHD Graphics,"15.6 inches, 1920 x 1080 pixels",Windows 11 OS,1 Year Warranty,4.70,57,37938,8 Threads,SSD,15.6 inches,1920 x 1080 pixels,0

# **EDA and Preprocessing**

## **Data Information**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 947 entries, 0 to 946
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   img              947 non-null    object
 1   name             947 non-null    object
 2   processor        947 non-null    object
 3   cores            913 non-null    object
 4   ram              947 non-null    object
 5   storage          947 non-null    object
 6   graphics_card    945 non-null    object
 7   screen_size      947 non-null    object
 8   os               947 non-null    object
 9   warranty         947 non-null    object
 10  rating           947 non-null    float64
 11  score            947 non-null    int64
 12  price            947 non-null    int64
 13  threads          859 non-null    object
 14  disk_type        946 non-null    object
 15  screen_size.1    947 non-null    object
 16  screen_pixels    942 non-null    object
 17  has_touchScreen  947 non-null    int64
dtypes: float64(1), int64(3), object(14)
memory usage: 133.3+ KB

## **Statistic Descriptive**

In [4]:
df.describe()

           rating       score          price  has_touchScreen
count  947.000000  947.000000     947.000000       947.000000
mean     4.363728   61.486800   89466.266103         0.119324
std      0.235783   11.706171   73107.114531         0.324341
min      4.000000   30.000000   10999.000000         0.000000
25%      4.150000   54.000000   47635.000000         0.000000
50%      4.350000   61.000000   68990.000000         0.000000
75%      4.550000   68.000000   99992.000000         0.000000
max      4.750000   98.000000  620990.000000         1.000000

## **Check Duplication**

In [5]:
print(df.duplicated().sum())

0

## **Check Missing Values**

In [6]:
df.isna().sum()

img                 0
name                0
processor           0
cores              34
ram                 0
storage             0
graphics_card       2
screen_size         0
os                  0
warranty            0
rating              0
score               0
price               0
threads            88
disk_type           1
screen_size.1       0
screen_pixels       5
has_touchScreen     0
dtype: int64

## **Data Cleaning**

In [7]:
df[df['graphics_card'].isna()]

,img,name,processor,cores,ram,storage,graphics_card,screen_size,os,warranty,rating,score,price,threads,disk_type,screen_size.1,screen_pixels,has_touchScreen
0,https://cdn1.smartprix.com/rx-iH0EKqLhw-w280-h...,Huawei MateBook Fold Laptop,Kirin X90,10 Cores,32 GB RAM,2 TB,NaN,"18 inches, 3296 x 2472 pixels, Touch Screen",HarmonyOS 5,1 Year Warranty,4.05,61,319930,NaN,SSD,18 inches,3296 x 2472 pixels,1
760,https://cdn1.smartprix.com/rx-in0iYt7IG-w280-h...,Lenovo YOGA Air 14s Laptop,Qualcomm Snapdragon X Elite X Elite,NaN,32 GB LPDDR5s RAM,1 TB,NaN,"14.5 inches, 1800 x 2920 pixels",Windows 11 OS,1 Year Warranty,4.50,47,114990,NaN,SSD,14.5 inches,1800 x 2920 pixels,0

In [8]:
laptop1 = df['name'] == 'Huawei MateBook Fold Laptop'

df.loc[laptop1 & df['graphics_card'].isna(), 'graphics_card'] = 'Maleoon 910B'

df[laptop1]

,img,name,processor,cores,ram,storage,graphics_card,screen_size,os,warranty,rating,score,price,threads,disk_type,screen_size.1,screen_pixels,has_touchScreen
0,https://cdn1.smartprix.com/rx-iH0EKqLhw-w280-h...,Huawei MateBook Fold Laptop,Kirin X90,10 Cores,32 GB RAM,2 TB,Maleoon 910B,"18 inches, 3296 x 2472 pixels, Touch Screen",HarmonyOS 5,1 Year Warranty,4.05,61,319930,NaN,SSD,18 inches,3296 x 2472 pixels,1

In [9]:
laptop2= df['name'] == 'Lenovo YOGA Air 14s Laptop'

df.loc[laptop2 & df['graphics_card'].isna(), 'graphics_card'] = 'Qualcomm Adreno GPU'

df[laptop2]

,img,name,processor,cores,ram,storage,graphics_card,screen_size,os,warranty,rating,score,price,threads,disk_type,screen_size.1,screen_pixels,has_touchScreen
760,https://cdn1.smartprix.com/rx-in0iYt7IG-w280-h...,Lenovo YOGA Air 14s Laptop,Qualcomm Snapdragon X Elite X Elite,NaN,32 GB LPDDR5s RAM,1 TB,Qualcomm Adreno GPU,"14.5 inches, 1800 x 2920 pixels",Windows 11 OS,1 Year Warranty,4.5,47,114990,NaN,SSD,14.5 inches,1800 x 2920 pixels,0

## **Imputation**

In [10]:
print(f'  cores   : {df["cores"].isna().sum()}')
print(f'  threads : {df["threads"].isna().sum()}')

  cores   : 34
  threads : 88

If the column value is NaN:
* Find the value from another laptop with the same processor.
* If there is no reference, fill in the string 'Unknown'.

If a value already exists, return it as is.

In [11]:
proc_cores_map   = df.dropna(subset=['cores']).groupby('processor')['cores'].first()
proc_threads_map = df.dropna(subset=['threads']).groupby('processor')['threads'].first()

def fill_from_processor(row, col, lookup_map):
    if pd.isna(row[col]):
        return lookup_map.get(row['processor'], 'Unknown')
    return row[col]

df['cores']   = df.apply(lambda row: fill_from_processor(row, 'cores',   proc_cores_map),   axis=1)
df['threads'] = df.apply(lambda row: fill_from_processor(row, 'threads', proc_threads_map), axis=1)

print('Number of NaNs after filling:')
print(f'  cores   : {df["cores"].isna().sum()}')
print(f'  threads : {df["threads"].isna().sum()}')
print()
print('Number of rows filled with \'Unknown\' (no processor reference):')
print(f'  cores   : {(df["cores"] == "Unknown").sum()}')
print(f'  threads : {(df["threads"] == "Unknown").sum()}')

Number of NaNs after filling:
  cores   : 0
  threads : 0

Number of rows filled with 'Unknown' (no processor reference):
  cores   : 22
  threads : 78

In [12]:
df[df['os'] == '2 USB 3.0 Ports']

,img,name,processor,cores,ram,storage,graphics_card,screen_size,os,warranty,rating,score,price,threads,disk_type,screen_size.1,screen_pixels,has_touchScreen
427,https://cdn1.smartprix.com/rx-iGpGCJNhH-w280-h...,"Primebook 2 Neo, 2025 Laptop (MediaTek Helio G...",MediaTek G99,6 GB DDR4 RAM,128 GB SSD,Mali-G57 MC2,"11.6 inches, 1366 x 768 pixels",1 Year Warranty,2 USB 3.0 Ports,1 Year Warranty,4.65,61,15990,Unknown,NaN,1 Year Warranty,NaN,0

In [13]:
df = df.drop(df[df['name'] == 'Primebook 2 Neo, 2025 Laptop (MediaTek Helio G99/ 6GB/ 128GB UFS 2.2/ PrimeOS 3.0'].index)

## **Convert Rupee to Rupiah**

In [14]:
# Approximate conversion rate: 1 INR to IDR is 183.40
inr_to_idr_rate = 183.40

df['price_idr'] = df['price'] * inr_to_idr_rate

# Display the first few rows with the new column
print("DataFrame with 'price_idr' column:")
print(df[['name', 'price', 'price_idr']].head())

DataFrame with 'price_idr' column:
                                  name   price   price_idr
0          Huawei MateBook Fold Laptop  319930  58675162.0
1     Lenovo V15 G4 ‎82C70081GE Laptop   33890   6215426.0
2          Dell G15-5530 Gaming Laptop   66800  12251120.0
3            Acer One 14 Z8-415 Laptop   22990   4216366.0
4  HP Victus 15-fb3012AX Gaming Laptop   66240  12148416.0

In [15]:
df['graphics_card'].nunique()

120

## **Make new Features**

### **1. Categorize Brand**

In [16]:
print(df['name'].str.split().str[0].value_counts())

name
HP           206
Lenovo       186
Asus         156
MSI          111
Acer         111
Dell          57
Apple         25
Samsung       23
Infinix       13
Microsoft      7
Gigabyte       6
Xiaomi         6
Thomson        5
Huawei         4
Motorola       4
Honor          4
Ultimus        3
Alienware      3
Colorful       3
Chuwi          2
ASUS           2
Tecno          2
Zebronics      1
Air            1
Avita          1
Razer          1
‎HP            1
‎Lenovo        1
Red            1
Name: count, dtype: int64

In [17]:
known_brands = [
    'HP', 'Lenovo', 'Asus', 'MSI', 'Acer', 'Dell', 'Apple', 'Samsung',
    'Infinix', 'Microsoft', 'Gigabyte', 'Xiaomi', 'Thomson', 'Huawei',
    'Motorola', 'Honor', 'Ultimus', 'Alienware', 'Colorful', 'Chuwi',
    'Tecno', 'Zebronics', 'Avita', 'Razer', 'Red Magic', 'Air Falcon'
]

brand_mapping = {
    'ASUS' : 'Asus',
    'Red'  : 'Red Magic',
    'Air'  : 'Air Falcon',
}

# Remove hidden character U+200E (Left-to-Right Mark) from the entire 'name' column
df['name'] = df['name'].str.replace('\u200e', '', regex=False)

# Extract the first word as brand
df['brand'] = df['name'].str.split().str[0].str.strip()

# Apply normalization mapping
df['brand'] = df['brand'].replace(brand_mapping)

# Validation
unknown = df[~df['brand'].isin(known_brands)]['brand'].value_counts()
print('Unknown Brands:')
print(unknown if not unknown.empty else 'None.')

print(f'Brand Distribution: {df['brand'].value_counts()}')

Unknown Brands:
None.
Brand Distribution: brand
HP            207
Lenovo        187
Asus          158
MSI           111
Acer          111
Dell           57
Apple          25
Samsung        23
Infinix        13
Microsoft       7
Xiaomi          6
Gigabyte        6
Thomson         5
Huawei          4
Motorola        4
Honor           4
Ultimus         3
Colorful        3
Alienware       3
Tecno           2
Chuwi           2
Zebronics       1
Avita           1
Air Falcon      1
Razer           1
Red Magic       1
Name: count, dtype: int64

### **2. Categorize Processor Brand**

Grouping processors into major brands: Intel, AMD, Snapdragon, MediaTek, Kirin, Apple.

In [18]:
def categorize_processor(proc):
  if pd.isna(proc):
    return 'Other'
  p = proc.lower()
  if 'apple' in p:
    return 'Apple'
  if 'intel' in p:
    return 'Intel'
  if 'amd' in p:
    return 'AMD'
  if 'snapdragon' in p:
    return 'Snapdragon'
  if 'mediatek' in p:
    return 'MediaTek'
  if 'kirin' in p:
    return 'Kirin'
  return 'Other'

df['processor_brand'] = df['processor'].apply(categorize_processor)

print(f'Processor Brand Distribution: {df['processor_brand'].value_counts()}')

Processor Brand Distribution: processor_brand
Intel         679
AMD           204
Snapdragon     31
Apple          25
MediaTek        6
Kirin           1
Name: count, dtype: int64

### **3. Categorize Price**

| Category | Price (IDR)        |
|----------|--------------------|
| Low      | < 10 Million       |
| Entry    |  10 – 15 Million   |
| Premium  |  15 – 30 Million   |
| Flagship |  > 30 Million      |

In [19]:
def categorize_price(price):
  if pd.isna(price):
    return 'Unknown'
  if price < 10_000_000:
    return 'Low'
  if price < 15_000_000:
    return 'Entry'
  if price < 30_000_000:
    return 'Premium'
  return 'Flagship'

df['price_category'] = df['price_idr'].apply(categorize_price)

print(f'Price Category Distribution: {df['price_category'].value_counts()}')

Price Category Distribution: price_category
Low         301
Entry       300
Premium     244
Flagship    101
Name: count, dtype: int64

### **4. Categorize Laptops**

Categories are determined based on the following **priority order**:

1. **MacBook** = Apple processor or name contains 'macbook'
2. **Chromebook** = name contains 'chromebook'
3. **Workstation** = Quadro/RTX A-series/RTX 2000/RTX 3000 GPU, or name contains ThinkPad P / ZBook / ProArt / MSI Creator
4. **Gaming** = GeForce RTX / Radeon RX / NVIDIA GPU
5. **2-in-1** = name contains Flex, Flip, Spectre, x360, ROG Flow, 2in1, Surface Pro, Spin
6. **Business** = name contains TravelMate, ExpertBook, Latitude, EliteBook, ProBook, ThinkPad
7. **Ultra** = processor ending in P/V, Snapdragon, Ryzen AI, 125H/225H/285H, or H-series without a gaming dGPU, with a price ≥ 15.000.000 IDR
8. **Daily** = MediaTek, Celeron, Pentium processor, or U-suffix with a price < IDR 15.000.000

In [20]:
def categorize_laptop(row):
    name  = str(row['name']).lower()          if pd.notna(row['name'])          else ''
    proc  = str(row['processor']).lower()     if pd.notna(row['processor'])     else ''
    gpu   = str(row['graphics_card']).lower() if pd.notna(row['graphics_card']) else ''
    price = row['price_idr']                  if pd.notna(row['price_idr'])          else 0
    proc_raw = str(row['processor'])          if pd.notna(row['processor'])     else ''

    # 1. MacBook
    if 'apple' in proc or 'macbook' in name:
        return 'MacBook'

    # 2. Chromebook
    if 'chromebook' in name:
        return 'Chromebook'

    # 3. Workstation
    workstation_gpu  = ['quadro', 'a500', 'rtx 2000', 'rtx 3000', 'rtx a', 'rtx 500']
    workstation_name = ['thinkpad p', 'zbook', 'proart', 'msi creator']
    if any(k in gpu for k in workstation_gpu) or any(k in name for k in workstation_name):
        return 'Workstation'

    # 4. Gaming
    gaming_gpu = ['geforce rtx', 'nvidia rtx', 'radeon rx', 'nvidia geforce', 'rtx 4', 'rtx 3', 'rtx 5', 'rtx 2050']
    if any(k in gpu for k in gaming_gpu):
        return 'Gaming'

    # 5. 2-in-1
    kw_2in1 = ['flex', 'flip', 'spectre', 'x360', 'rog flow', '2in1', '2-in-1', 'surface pro', 'spin']
    if any(k in name for k in kw_2in1):
        return '2-in-1'

    # 6. Business
    business_kw = ['travelmate', 'expertbook', 'latitude', 'elitebook', 'probook', 'thinkpad']
    if any(k in name for k in business_kw):
        return 'Business'

    # 7. Ultrabook
    is_suffix_pv  = bool(re.search(r'\b\d+[PV]\b', proc_raw))
    is_snapdragon = 'snapdragon' in proc or 'qualcomm' in proc
    is_ryzen_ai   = 'ryzen ai' in proc
    is_h_special  = bool(re.search(r'\b(125H|155H|185H|225H|255H|285H)\b', proc_raw))
    is_h_no_dgpu  = bool(re.search(r'\d+HS?\b', proc_raw)) and \
                    not any(k in gpu for k in ['rtx', 'radeon rx', 'radeon fx'])
    if (is_suffix_pv or is_snapdragon or is_ryzen_ai or is_h_special or is_h_no_dgpu) and price >= 10_000_000:
        return 'Ultrabook'

    # 8. Daily
    daily_proc    = ['mediatek', 'celeron', 'pentium']
    is_suffix_u   = bool(re.search(r'\d+U\b', proc_raw))
    if any(k in proc for k in daily_proc) or \
       (is_suffix_u and price < 10_000_000) or \
       (is_snapdragon and price < 10_000_000):
        return 'Daily'

    return 'Daily'


df['laptop_category'] = df.apply(categorize_laptop, axis=1)

print(f'Price Category Distribution: {df['laptop_category'].value_counts()}')

Price Category Distribution: laptop_category
Gaming         322
Daily          317
Ultrabook      179
Business        38
2-in-1          34
MacBook         25
Chromebook      16
Workstation     15
Name: count, dtype: int64

### **5. Categorize RAM**

In [21]:
ram_extracted = df['ram'].str.extract(r'(\d+)\s*GB', expand=False)
df['ram_gb'] = pd.to_numeric(ram_extracted, errors='coerce').astype('Int64')

print(df[['ram', 'ram_gb']].head(5))
print(f'NaN: {df["ram_gb"].isna().sum()}')

              ram  ram_gb
0       32 GB RAM      32
1  16 GB DDR5 RAM      16
2  16 GB DDR5 RAM      16
3   8 GB DDR4 RAM       8
4  16 GB DDR5 RAM      16
NaN: 0

### **6. Categorize Storage**

In [22]:
def parse_storage(val):
    val = str(val).strip()
    match_tb = re.search(r'(\d+(?:\.\d+)?)\s*TB', val, re.IGNORECASE)
    match_gb = re.search(r'(\d+)\s*GB', val, re.IGNORECASE)
    if match_tb:
        return int(float(match_tb.group(1)) * 1024)
    if match_gb:
        return int(match_gb.group(1))
    return pd.NA

df['storage_gb'] = df['storage'].apply(parse_storage)
df['storage_gb'] = pd.to_numeric(df['storage_gb'], errors='coerce').astype('Int64')

print(df[['storage', 'storage_gb']].head(5))
print(f'NaN: {df["storage_gb"].isna().sum()}')

    storage  storage_gb
0    2 TB          2048
1  512 GB           512
2    1 TB          1024
3  512 GB           512
4  512 GB           512
NaN: 0

### **7. Categorize GPU**

In [23]:
def categorize_gpu(gpu):
    if pd.isna(gpu):
        return 'Integrated'
    g = gpu.lower()

    if any(k in g for k in ['rtx', 'gtx', 'quadro', 'nvidia']):
        return 'NVIDIA'
    if any(k in g for k in ['radeon rx', 'radeon 8', 'radeon 6', 'radeon vega']):
        return 'AMD Dedicated'
    if re.search(r'arc\s+a\d{3}', g):
        return 'Intel Arc Dedicated'
    if 'adreno' in g:
        return 'Qualcomm Adreno'
    if 'maleoon' in g:
        return 'Kirin Maleoon'
    if any(k in g for k in ['mali', 'immortalis']):
        return 'ARM Mali'
    if 'apple' in g or re.search(r'\d+-core gpu', g):
        return 'Apple GPU'
    return 'Integrated'

df['gpu_type'] = df['graphics_card'].apply(categorize_gpu)

print(df['gpu_type'].value_counts())

gpu_type
Integrated             538
NVIDIA                 332
Qualcomm Adreno         31
AMD Dedicated           20
Apple GPU               17
ARM Mali                 6
Kirin Maleoon            1
Intel Arc Dedicated      1
Name: count, dtype: int64

# **Modelling**

### **1. Combined text feature**

In [24]:
df['combined_text'] = (
    df['brand']             + ' ' +
    df['processor_brand']   + ' ' +
    df['laptop_category']   + ' ' +
    df['price_category']    + ' ' +
    df['gpu_type']          + ' ' +
    df['os'].fillna('')     + ' ' +
    df['disk_type'].fillna('')
)

### **2. TF-IDF pada combined text**

In [25]:
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(df['combined_text'])

print('TF-IDF matrix shape:', tfidf_matrix.shape)

TF-IDF matrix shape: (946, 67)

### **3. Normalize Numerical Feature**

In [26]:
num_cols = ['ram_gb', 'storage_gb', 'price_idr', 'rating']

df_num = df[num_cols].copy()
df_num['ram_gb'] = df_num['ram_gb'].fillna(df_num['ram_gb'].median())
df_num['storage_gb'] = df_num['storage_gb'].fillna(df_num['storage_gb'].median())

scaler = MinMaxScaler()
num_scaled = scaler.fit_transform(df_num)

print('Numerical matrix shape:', num_scaled.shape)

Numerical matrix shape: (946, 4)

### **4. Combine TF-IDF + numerik = Cosine Similarity**

In [27]:
weight_text = 0.6
weight_num = 0.4

num_sparse = sp.csr_matrix(num_scaled * weight_num)
tfidf_weighted = tfidf_matrix * weight_text

combined_matrix = sp.hstack([tfidf_weighted, num_sparse])
cosine_sim = cosine_similarity(combined_matrix, combined_matrix)

print('Combined matrix shape:', combined_matrix.shape)

Combined matrix shape: (946, 71)

### **5. Recommendation**

In [29]:
df = df.reset_index(drop=True)
indices = pd.Series(df.index, index=df['name'])

laptop_input = 'Asus Gaming V16 2025 V3607VH-RP038WS Laptop'
top_n = 10

idx = indices[laptop_input]
scores = list(enumerate(cosine_sim[idx]))
scores = sorted(scores, key=lambda x: x[1], reverse=True)
scores = scores[1:top_n+1]

result_idx = [i[0] for i in scores]

cols_show = ['name', 'processor', 'graphics_card', 'ram_gb', 'screen_size', 'storage', 'os',
             'price_idr', 'rating', 'laptop_category']

print(f'Rekomendasi untuk: {laptop_input}\n')
df.iloc[result_idx][cols_show]

Rekomendasi untuk: Asus Gaming V16 2025 V3607VH-RP038WS Laptop

,name,processor,graphics_card,ram_gb,screen_size,storage,os,price_idr,rating,laptop_category
178,Asus TUF Gaming F15 FX507VV-LP287W Gaming Laptop,13th Gen Intel Core i7 13620H,8 GB NVIDIA GeForce RTX 4060,16,"15.6 inches, 1920 x 1080 pixels",512 GB,Windows 11 OS,18338166.0,4.05,Gaming
251,Asus TUF Gaming F16 FX677VU-RL155WS Laptop,13th Gen Intel Core i7 13620H,6 GB NVIDIA GeForce RTX 4050,16,"16 inches, 1920 x 1200 pixels",512 GB,Windows 11 OS,17421166.0,4.05,Gaming
413,Asus Gaming V16 2025 V3607VH-RP037WS Laptop,5th Gen Intel Core 5 210H,8 GB NVIDIA GeForce RTX 5050,16,"16 inches, 1920 x 1200 pixels",512 GB,Windows 11 OS,18888366.0,4.00,Gaming
769,Asus TUF Gaming F15 FX507VU-LP210W Gaming Laptop,13th Gen Intel Core i7 13620H,6 GB NVIDIA GeForce RTX 4050,16,"15.6 inches, 1920 x 1080 pixels",512 GB,Windows 11 OS,17054366.0,4.20,Gaming
115,Asus TUF Gaming F16 FX677VU-RL055WS Laptop,5th Gen Intel Core 5 210H,6 GB NVIDIA GeForce RTX 4050,16,"16 inches, 1920 x 1200 pixels",512 GB,Windows 11 OS,15587166.0,4.20,Gaming
454,Asus TUF Gaming F16 FX608JH-RV057WS Laptop,13th Gen Intel Core i5 13450HX,8 GB NVIDIA GeForce RTX 5050,16,"16 inches, 1920 x 1200 pixels",1 TB,Windows 11 OS,22006166.0,4.20,Gaming
98,Asus ROG Strix G16 G615JHR-S5005WS Gaming Laptop,14th Gen Intel Core i7 14650HX,8 GB NVIDIA GeForce RTX 5050,16,"16 inches, 2560 x 1600 pixels",1 TB,Windows 11 OS,29342166.0,4.30,Gaming
576,Asus Gaming V16 V3607VU-RP275WS Laptop,7th Gen Intel Core 7 240H,6 GB NVIDIA GeForce RTX 4050,16,"16 inches, 1920 x 1200 pixels",512 GB,Windows 11 OS,16137366.0,4.45,Gaming
582,Asus TUF Gaming F15 FX507VV-LP487WS Gaming Laptop,13th Gen Intel Core i7 13620H,8 GB NVIDIA GeForce RTX 4060,16,"15.6 inches, 1920 x 1080 pixels",1 TB,Windows 11 OS,19255166.0,4.50,Gaming
432,Asus Gaming V16 V3607VM-RP057WS Laptop,7th Gen Intel Core 7 240H,8 GB NVIDIA GeForce RTX 5060,16,"16 inches, 1920 x 1200 pixels",512 GB,Windows 11 OS,22006166.0,4.65,Gaming

### **6. Search no Cosine Similarity**

In [28]:
laptop_input = 'Asus Gaming V16'
matched = df[df['name'].str.contains(laptop_input, case=False, na=False)]

if matched.empty:
    print(f'Laptop "{laptop_input}" tidak ditemukan.')
else:
    print(f'Ditemukan {len(matched)} laptop:\n')
    for name in matched['name'].values:
        print(f'  - {name}')

Ditemukan 4 laptop:

  - Asus Gaming V16 2025 V3607VH-RP038WS Laptop
  - Asus Gaming V16 2025 V3607VH-RP037WS Laptop
  - Asus Gaming V16 V3607VM-RP057WS Laptop
  - Asus Gaming V16 V3607VU-RP275WS Laptop

# **Streamlit Preparation**

In [30]:
import joblib

joblib.dump(cosine_sim, 'cosine_sim.pkl')
joblib.dump(tfidf, 'tfidf.pkl')
joblib.dump(scaler, 'scaler.pkl')
df.to_csv('laptop_cleaned.csv', index=False)

print('Export selesai.')

Export selesai.